name: Build LaTeX PDF

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up TeX Live
      uses: xu-cheng/latex-action@v3
      with:
        root_file: slides__Copy_/main.tex  # <-- Change to your main tex file name

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-pdf
        path: latex_presentation_hsmw.pdf  # <-- Change to your output PDF name
